image: node:4.2.4
services:
   - registry.cloudf.de/matthias/depostgresdocker:latest
#  - postgres:9.5.0

variables:
  POSTGRES_DB: smartbackendevelopment
  POSTGRES_USER: smartinsurance
  POSTGRES_PASSWORD: "123456"

stages:
  - test

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.de

mochatest:
  stage: test
  script:
    - cd ./ExpressForDevelopment/ && npm config set loglevel warn && npm install --loglevel warn
    - echo "exports.url = 'postgres://smartinsurance:123456@postgres/smartbackendevelopment';" > ./node_modules/dbconfig.js
    - echo "exports.url = 'postgres://smartinsurance:123456@postgres/smartbackendevelopment';" > ./test/modules/testdbconfig.js;
#    - cat ./node_modules/dbconfig.js
#    - cat ./test/modules/testdbconfig.js
    - npm install pg --loglevel warn
    - npm install fs --loglevel warn
#    - npm --version
#    - node --version
#    - ls -la
#    - node dbsetup.js  # sollte nun im Test integriert sein?
    - npm install mocha -g --loglevel warn
    - npm test
