image: node:4.2.4
services:
  - postgres:9.5.0

variables:
  POSTGRES_DB: smartbackendevelopment
  POSTGRES_USER: smartinsurance
  POSTGRES_PASSWORD: "123456"

stages:
  - test

mochatest:
  stage: test
  script:
    - cd ./ExpressForDevelopment/ && npm install
    - echo "exports.url = 'postgres://smartinsurance:123456@postgres/smartbackendevelopment';" > ./node_modules/dbconfig.js
    - cat ./node_modules/dbconfig.js
    - npm install pg
    - npm install fs
    - npm --version
    - node --version
    - ls -la
    - node dbsetup.js
    - npm install mocha -g
    - mocha
