image: docker:git
services:
- docker:dind

stages:
- build
- test
- release
- deploy

variables:
  CONTAINER_TEST_IMAGE: registry.cloudf.de/matthias/testci:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.cloudf.de/matthias/testci:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.cloudf.de

build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
