image: node:4.2.4
services:
  - postgres:9.5.0

variables:
  POSTGRES_DB: smartbackendevelopment
  POSTGRES_USER: smartinsurance
  POSTGRES_PASSWORD: "123456"

stages:
  - prepare
  - database
  - test

prepare npm:
  stage: prepare
  script:
    - cd ./ExpressForDevelopment/ && npm install
    - echo "exports.url = 'postgres://smartinsurance:123456@postgres/smartbackendevelopment';" > ./node_modules/dbconfig.js
    - cat ./node_modules/dbconfig.js
    - npm install pg
    - npm install fs
    - npm install mocha -g

prepare database:
  stage: database
  script:
    - cd ./ExpressForDevelopment/
    - echo "exports.url = 'postgres://smartinsurance:123456@postgres/smartbackendevelopment';" > ./node_modules/dbconfig.js
    - cat ./node_modules/dbconfig.js
    - npm install pg
    - npm install fs
    - node dbsetup.js

mochatest:
  stage: test
  script:
    - cd ./ExpressForDevelopment/
    - echo "exports.url = 'postgres://smartinsurance:123456@postgres/smartbackendevelopment';" > ./node_modules/dbconfig.js
    - cat ./node_modules/dbconfig.js
    - ls -la
    - npm install mocha -g
    - mocha
