test:
  image: node:4.2.2
  services:
    - postgres:9.5.0
  tags:
    - docker
  script:
    - cd ./ExpressForDevelopment/ && npm install
    - pg_dump --help
    - npm --version
    - nodejs --version
    - psql --version
